/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Nrnb2026ParticipeRouteImport } from './routes/nrnb2026-participe'
import { Route as Nrnb2026NovaRouteImport } from './routes/nrnb2026-nova'
import { Route as Nrnb20262RouteImport } from './routes/nrnb2026-2'
import { Route as Nrnb20261RouteImport } from './routes/nrnb2026-1'
import { Route as Nrnb2026RouteImport } from './routes/nrnb2026'
import { Route as EspecialRouteImport } from './routes/especial'
import { Route as R2por1RouteImport } from './routes/2por1'
import { Route as IndexRouteImport } from './routes/index'

const Nrnb2026ParticipeRoute = Nrnb2026ParticipeRouteImport.update({
  id: '/nrnb2026-participe',
  path: '/nrnb2026-participe',
  getParentRoute: () => rootRouteImport,
} as any)
const Nrnb2026NovaRoute = Nrnb2026NovaRouteImport.update({
  id: '/nrnb2026-nova',
  path: '/nrnb2026-nova',
  getParentRoute: () => rootRouteImport,
} as any)
const Nrnb20262Route = Nrnb20262RouteImport.update({
  id: '/nrnb2026-2',
  path: '/nrnb2026-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Nrnb20261Route = Nrnb20261RouteImport.update({
  id: '/nrnb2026-1',
  path: '/nrnb2026-1',
  getParentRoute: () => rootRouteImport,
} as any)
const Nrnb2026Route = Nrnb2026RouteImport.update({
  id: '/nrnb2026',
  path: '/nrnb2026',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialRoute = EspecialRouteImport.update({
  id: '/especial',
  path: '/especial',
  getParentRoute: () => rootRouteImport,
} as any)
const R2por1Route = R2por1RouteImport.update({
  id: '/2por1',
  path: '/2por1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2por1': typeof R2por1Route
  '/especial': typeof EspecialRoute
  '/nrnb2026': typeof Nrnb2026Route
  '/nrnb2026-1': typeof Nrnb20261Route
  '/nrnb2026-2': typeof Nrnb20262Route
  '/nrnb2026-nova': typeof Nrnb2026NovaRoute
  '/nrnb2026-participe': typeof Nrnb2026ParticipeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2por1': typeof R2por1Route
  '/especial': typeof EspecialRoute
  '/nrnb2026': typeof Nrnb2026Route
  '/nrnb2026-1': typeof Nrnb20261Route
  '/nrnb2026-2': typeof Nrnb20262Route
  '/nrnb2026-nova': typeof Nrnb2026NovaRoute
  '/nrnb2026-participe': typeof Nrnb2026ParticipeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2por1': typeof R2por1Route
  '/especial': typeof EspecialRoute
  '/nrnb2026': typeof Nrnb2026Route
  '/nrnb2026-1': typeof Nrnb20261Route
  '/nrnb2026-2': typeof Nrnb20262Route
  '/nrnb2026-nova': typeof Nrnb2026NovaRoute
  '/nrnb2026-participe': typeof Nrnb2026ParticipeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/2por1'
    | '/especial'
    | '/nrnb2026'
    | '/nrnb2026-1'
    | '/nrnb2026-2'
    | '/nrnb2026-nova'
    | '/nrnb2026-participe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/2por1'
    | '/especial'
    | '/nrnb2026'
    | '/nrnb2026-1'
    | '/nrnb2026-2'
    | '/nrnb2026-nova'
    | '/nrnb2026-participe'
  id:
    | '__root__'
    | '/'
    | '/2por1'
    | '/especial'
    | '/nrnb2026'
    | '/nrnb2026-1'
    | '/nrnb2026-2'
    | '/nrnb2026-nova'
    | '/nrnb2026-participe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2por1Route: typeof R2por1Route
  EspecialRoute: typeof EspecialRoute
  Nrnb2026Route: typeof Nrnb2026Route
  Nrnb20261Route: typeof Nrnb20261Route
  Nrnb20262Route: typeof Nrnb20262Route
  Nrnb2026NovaRoute: typeof Nrnb2026NovaRoute
  Nrnb2026ParticipeRoute: typeof Nrnb2026ParticipeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nrnb2026-participe': {
      id: '/nrnb2026-participe'
      path: '/nrnb2026-participe'
      fullPath: '/nrnb2026-participe'
      preLoaderRoute: typeof Nrnb2026ParticipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nrnb2026-nova': {
      id: '/nrnb2026-nova'
      path: '/nrnb2026-nova'
      fullPath: '/nrnb2026-nova'
      preLoaderRoute: typeof Nrnb2026NovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nrnb2026-2': {
      id: '/nrnb2026-2'
      path: '/nrnb2026-2'
      fullPath: '/nrnb2026-2'
      preLoaderRoute: typeof Nrnb20262RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nrnb2026-1': {
      id: '/nrnb2026-1'
      path: '/nrnb2026-1'
      fullPath: '/nrnb2026-1'
      preLoaderRoute: typeof Nrnb20261RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nrnb2026': {
      id: '/nrnb2026'
      path: '/nrnb2026'
      fullPath: '/nrnb2026'
      preLoaderRoute: typeof Nrnb2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especial': {
      id: '/especial'
      path: '/especial'
      fullPath: '/especial'
      preLoaderRoute: typeof EspecialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2por1': {
      id: '/2por1'
      path: '/2por1'
      fullPath: '/2por1'
      preLoaderRoute: typeof R2por1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2por1Route: R2por1Route,
  EspecialRoute: EspecialRoute,
  Nrnb2026Route: Nrnb2026Route,
  Nrnb20261Route: Nrnb20261Route,
  Nrnb20262Route: Nrnb20262Route,
  Nrnb2026NovaRoute: Nrnb2026NovaRoute,
  Nrnb2026ParticipeRoute: Nrnb2026ParticipeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
